defmodule LeetcodeTest do
  use ExUnit.Case
  doctest TwoSum
  doctest AddTwoNumbers
  doctest PalindromeNumber
  doctest RomanToInteger
  doctest ValidParentheses
  doctest RangeCovered
  doctest DecompressRunLengthEncodedList
  doctest PerfectNumber
  doctest PlusOne
  doctest ValidPalindrome
  doctest PascalsTriangle
  doctest ReverseInteger
  doctest LengthOfLastWord
  doctest AddBinary
  doctest ClimbingStairs
  doctest Sqrt
  doctest DailyTemperatures
  doctest ContainerWithMostWater
  doctest SearchInsertPosition
  doctest RemoveDuplicatesFromSortedList
  doctest LetterCombinationsOfAPhoneNumber
  doctest LengthOfLongestSubstring
  doctest UniquePaths
  doctest LongestCommonPrefix
  doctest FindDisappearedNumbers
  doctest StrStr
  doctest HammingDistance
  doctest SingleNonDuplicate
  doctest BuildTree
  doctest DeleteNode
  doctest InorderTraversal
  doctest IntervalIntersection
  doctest MaxSubArray
  doctest GetRow
  doctest MaxProfit
  doctest Permute
  doctest ProductExceptSelf
  doctest PreorderTraversal
  doctest PostorderTraversal
  doctest AllPathsSourceTarget
  doctest AccountsMerge
  doctest MaximalRectangle
  doctest LargestRectangleArea
  doctest FindJudge
  doctest BitwiseComplement
  doctest Partition
  doctest CarPooling
  doctest CherryPickup
  doctest IsRobotBounded
  doctest InsertIntoBst
  doctest FindMinArrowShots
  doctest MyAtoi
  doctest MinJumps
  doctest MaxDistToClosest
  doctest WordPattern
  doctest CanPlaceFlowers
  doctest CanCompleteCircuit
  doctest DetectCapitalUse
  doctest MaximumWealth
  doctest FindTheDifference
end
